from __future__ import annotations

import pandas as pd


def preserve_runtime_fields(df: pd.DataFrame, out: pd.DataFrame, fields: tuple[str, ...]) -> pd.DataFrame:
    """
    Carry runtime-only fields through prep when the generated spec does not list them.

    The parity work is ahead of the spec generator in a few places. This helper
    lets prep keep important comparison/order metadata without widening the base
    contract for every chart.
    """
    for field in fields:
        if field in df.columns and field not in out.columns:
            out[field] = df[field]
    return out


def ordered_unique(values) -> list[str]:
    seen: list[str] = []
    for value in values:
        if pd.isna(value):
            continue
        text = str(value).strip()
        if text and text not in seen:
            seen.append(text)
    return seen


def percentile_rank(values: pd.Series, *, higher_is_better: bool = True) -> pd.Series:
    numeric = pd.to_numeric(values, errors="coerce")
    out = pd.Series([float("nan")] * len(numeric), index=numeric.index, dtype="float64")
    finite = numeric.dropna()
    if finite.empty:
        return out

    ranks = finite.rank(method="average", ascending=True if higher_is_better else False, pct=True)
    out.loc[finite.index] = ranks * 100.0
    return out


def format_numeric_labels(values: pd.Series, *, decimals: int = 1, missing_label: str = "No data") -> pd.Series:
    numeric = pd.to_numeric(values, errors="coerce")
    labels = pd.Series([missing_label] * len(numeric), index=numeric.index, dtype="object")
    finite_mask = numeric.notna()
    if finite_mask.any():
        labels.loc[finite_mask] = numeric.loc[finite_mask].map(lambda value: f"{value:,.{decimals}f}")
    return labels


def complete_matrix(
    df: pd.DataFrame,
    *,
    row_fields: tuple[str, ...],
    column_fields: tuple[str, ...],
    value_key_fields: tuple[str, ...] = ("row_id", "column_id"),
) -> pd.DataFrame:
    """
    Fill in the full row/column grid so missing cells render explicitly.

    Heatmap-style charts need an explicit matrix surface or the renderer cannot
    distinguish "missing cell" from "cell never generated by prep".
    """
    row_lookup = df.loc[:, [field for field in row_fields if field in df.columns]].drop_duplicates().copy()
    column_lookup = df.loc[:, [field for field in column_fields if field in df.columns]].drop_duplicates().copy()
    grid = row_lookup.merge(column_lookup, how="cross")
    passthrough_columns = [
        column
        for column in df.columns
        if column not in set(row_lookup.columns).union(column_lookup.columns) or column in value_key_fields
    ]
    value_df = df.loc[:, passthrough_columns].copy()
    return grid.merge(value_df, how="left", on=list(value_key_fields))
