"""Deterministic SQL generation from structured query plans."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from chatbot.query.catalogs import load_semantic_catalogs


READ_ONLY_CTE_HINT = "-- Generated by QueryGenerator. Read-only analytical SQL."


@dataclass
class RenderedQuery:
    """Generated SQL plus semantic metadata used by validation and execution."""

    template_id: str
    sql: str
    tables_used: list[str]
    fields_used: dict[str, set[str]]
    joins_used: list[str]
    geo_level: str | None
    metric_ids: list[str]
    plan: dict[str, Any]


class QueryGenerator:
    """Render approved semantic templates into executable DuckDB SQL."""

    def __init__(self) -> None:
        self.catalogs = load_semantic_catalogs()

    def render(self, plan: dict[str, Any]) -> RenderedQuery:
        template_id = plan.get("template_id") or plan.get("question_type")
        if template_id not in self.catalogs["templates"]:
            raise ValueError(f"Unsupported template_id: {template_id}")
        self._validate_required_slots(template_id, plan)

        if template_id == "growth":
            return self._render_growth(plan)

        metric = self._get_metric(plan["metric_id"])
        table_id = plan.get("source_table") or metric["source_table"]
        template = getattr(self, f"_render_{template_id}")
        return template(plan, metric, table_id)

    def _render_ranking(
        self, plan: dict[str, Any], metric: dict[str, Any], table_id: str
    ) -> RenderedQuery:
        sql = f"""
{READ_ONLY_CTE_HINT}
SELECT
  base.geo_level,
  base.geo_id,
  base.geo_name,
  base.year,
  base.{metric["source_column"]} AS metric_value,
  '{metric["metric_id"]}' AS metric_id,
  '{self._escape_sql_string(metric["display_name"])}' AS metric_label,
  ROW_NUMBER() OVER (
    ORDER BY base.{metric["source_column"]} {self._sql_sort_direction(plan["sort_direction"])}, base.geo_name ASC
  ) AS rank
FROM {self._qualified_table(table_id)} AS base
WHERE {self._base_where_clause(plan, table_id, metric)}
ORDER BY metric_value {self._sql_sort_direction(plan["sort_direction"])}, geo_name ASC
LIMIT {self._validated_limit(plan.get("limit", 10))}
""".strip()
        return self._rendered_query(
            template_id="ranking",
            sql=sql,
            table_id=table_id,
            fields={
                "geo_level",
                "geo_id",
                "geo_name",
                "year",
                metric["source_column"],
            }
            | self._filter_fields(plan),
            geo_level=plan["geo_level"],
            metric_ids=[metric["metric_id"]],
            plan=plan,
        )

    def _render_trend(
        self, plan: dict[str, Any], metric: dict[str, Any], table_id: str
    ) -> RenderedQuery:
        sql = f"""
{READ_ONLY_CTE_HINT}
SELECT
  base.geo_level,
  base.geo_id,
  base.geo_name,
  base.year AS period,
  base.{metric["source_column"]} AS metric_value,
  '{metric["metric_id"]}' AS metric_id,
  '{self._escape_sql_string(metric["display_name"])}' AS metric_label
FROM {self._qualified_table(table_id)} AS base
WHERE {self._trend_where_clause(plan, table_id, metric)}
ORDER BY base.geo_name ASC, period ASC
""".strip()
        return self._rendered_query(
            template_id="trend",
            sql=sql,
            table_id=table_id,
            fields={
                "geo_level",
                "geo_id",
                "geo_name",
                "year",
                metric["source_column"],
            }
            | self._filter_fields(plan),
            geo_level=plan["geo_level"],
            metric_ids=[metric["metric_id"]],
            plan=plan,
        )

    def _render_compare_selected(
        self, plan: dict[str, Any], metric: dict[str, Any], table_id: str
    ) -> RenderedQuery:
        geo_ids = plan["geo_ids"]
        order_expr = self._preserve_order_case("base.geo_id", geo_ids)
        sql = f"""
{READ_ONLY_CTE_HINT}
SELECT
  base.geo_level,
  base.geo_id,
  base.geo_name,
  base.year,
  base.{metric["source_column"]} AS metric_value,
  '{metric["metric_id"]}' AS metric_id,
  '{self._escape_sql_string(metric["display_name"])}' AS metric_label
FROM {self._qualified_table(table_id)} AS base
WHERE {self._compare_where_clause(plan, table_id, metric)}
ORDER BY {order_expr}, base.geo_name ASC
""".strip()
        return self._rendered_query(
            template_id="compare_selected",
            sql=sql,
            table_id=table_id,
            fields={"geo_level", "geo_id", "geo_name", "year", metric["source_column"]},
            geo_level=plan["geo_level"],
            metric_ids=[metric["metric_id"]],
            plan=plan,
        )

    def _render_distribution(
        self, plan: dict[str, Any], metric: dict[str, Any], table_id: str
    ) -> RenderedQuery:
        target_geo_id = plan.get("target_geo_id")
        highlight_sql = (
            f"CASE WHEN base.geo_id = {self._sql_literal(target_geo_id)} THEN TRUE ELSE FALSE END"
            if target_geo_id
            else "FALSE"
        )
        sql = f"""
{READ_ONLY_CTE_HINT}
SELECT
  base.geo_level,
  base.geo_id,
  base.geo_name,
  base.year,
  base.{metric["source_column"]} AS metric_value,
  '{metric["metric_id"]}' AS metric_id,
  '{self._escape_sql_string(metric["display_name"])}' AS metric_label,
  {highlight_sql} AS highlight_flag
FROM {self._qualified_table(table_id)} AS base
WHERE {self._base_where_clause(plan, table_id, metric)}
ORDER BY metric_value DESC, geo_name ASC
""".strip()
        fields = {"geo_level", "geo_id", "geo_name", "year", metric["source_column"]}
        if target_geo_id:
            fields.add("geo_id")
        return self._rendered_query(
            template_id="distribution",
            sql=sql,
            table_id=table_id,
            fields=fields | self._filter_fields(plan),
            geo_level=plan["geo_level"],
            metric_ids=[metric["metric_id"]],
            plan=plan,
        )

    _REFERENCE_BENCHMARK_TYPES = frozenset({"us", "region", "division"})

    def _render_benchmark(
        self, plan: dict[str, Any], metric: dict[str, Any], table_id: str
    ) -> RenderedQuery:
        benchmark_type = plan["benchmark_type"]
        benchmark_label = plan.get("comparison_label") or benchmark_type.replace("_", " ").title()
        benchmark_geo_level = (
            plan.get("benchmark_geo_level")
            or (benchmark_type if benchmark_type in self.catalogs["geo_levels"] else None)
            or plan["target_geo_level"]
        )

        if benchmark_type in self._REFERENCE_BENCHMARK_TYPES:
            benchmark_cte = self._benchmark_cte_from_reference(
                plan,
                metric,
                table_id,
                benchmark_label,
                benchmark_geo_level,
            )
        else:
            benchmark_cte = self._benchmark_cte_inline(plan, metric, table_id, benchmark_label, benchmark_geo_level)

        sql = f"""
{READ_ONLY_CTE_HINT}
WITH target AS (
  SELECT
    base.geo_level,
    base.geo_id,
    base.geo_name,
    base.year,
    base.{metric["source_column"]} AS metric_value,
    'target' AS comparison_group
  FROM {self._qualified_table(table_id)} AS base
  WHERE base.geo_level = {self._sql_literal(plan["target_geo_level"])}
    AND base.geo_id = {self._sql_literal(plan["target_geo_id"])}
    AND base.year = {self._sql_literal(plan["year"])}
    AND base.{metric["source_column"]} IS NOT NULL
),
{benchmark_cte}
SELECT
  geo_level,
  geo_id,
  geo_name,
  year,
  metric_value,
  '{metric["metric_id"]}' AS metric_id,
  '{self._escape_sql_string(metric["display_name"])}' AS metric_label,
  comparison_group
FROM target
UNION ALL
SELECT
  geo_level,
  geo_id,
  geo_name,
  year,
  metric_value,
  '{metric["metric_id"]}' AS metric_id,
  '{self._escape_sql_string(metric["display_name"])}' AS metric_label,
  comparison_group
FROM benchmark
ORDER BY comparison_group ASC
""".strip()
        fields = {"geo_level", "geo_id", "geo_name", "year", metric["source_column"]}
        return self._rendered_query(
            template_id="benchmark",
            sql=sql,
            table_id=table_id,
            fields=fields,
            geo_level=plan["target_geo_level"],
            metric_ids=[metric["metric_id"]],
            plan={**plan, "benchmark_geo_level": benchmark_geo_level},
        )

    def _benchmark_cte_from_reference(
        self,
        plan: dict[str, Any],
        metric: dict[str, Any],
        table_id: str,
        benchmark_label: str,
        benchmark_geo_level: str,
    ) -> str:
        """Benchmark CTE that prefers gold.benchmark_reference with an inline fallback."""
        benchmark_geo_id_filter = ""
        if plan.get("benchmark_geo_ids"):
            benchmark_geo_id_filter = (
                f"AND ref.benchmark_geo_id IN ({self._sql_list(plan['benchmark_geo_ids'])})"
            )
        inline_cte = self._benchmark_cte_inline(
            plan,
            metric,
            table_id,
            benchmark_label,
            benchmark_geo_level,
            cte_name="benchmark_inline",
        )
        return f"""reference_benchmark AS (
  SELECT
    ref.benchmark_level AS geo_level,
    ref.benchmark_geo_id AS geo_id,
    ref.benchmark_label AS geo_name,
    ref.year,
    ref.metric_value,
    'benchmark' AS comparison_group
  FROM gold.benchmark_reference ref
  WHERE ref.benchmark_level = {self._sql_literal(plan["benchmark_type"])}
    AND ref.source_table = {self._sql_literal(table_id)}
    AND ref.metric_id = {self._sql_literal(metric["metric_id"])}
    AND ref.year = {self._sql_literal(plan["year"])}
    {benchmark_geo_id_filter}
    AND ref.metric_value IS NOT NULL
),
{inline_cte},
benchmark AS (
  SELECT * FROM reference_benchmark
  UNION ALL
  SELECT * FROM benchmark_inline
  WHERE NOT EXISTS (SELECT 1 FROM reference_benchmark)
)"""

    def _benchmark_cte_inline(
        self,
        plan: dict[str, Any],
        metric: dict[str, Any],
        table_id: str,
        benchmark_label: str,
        benchmark_geo_level: str,
        cte_name: str = "benchmark",
    ) -> str:
        """Benchmark CTE that computes inline from the source table (peer benchmarks)."""
        benchmark_where = self._benchmark_where_clause(plan, benchmark_geo_level)
        return f"""{cte_name} AS (
  SELECT
    {self._sql_literal(benchmark_geo_level)} AS geo_level,
    {self._sql_literal(plan.get("benchmark_geo_ids", [benchmark_label])[0])} AS geo_id,
    {self._sql_literal(benchmark_label)} AS geo_name,
    {self._sql_literal(plan["year"])} AS year,
    AVG(base.{metric["source_column"]}) AS metric_value,
    'benchmark' AS comparison_group
  FROM {self._qualified_table(table_id)} AS base
  WHERE {benchmark_where}
    AND base.year = {self._sql_literal(plan["year"])}
    AND base.{metric["source_column"]} IS NOT NULL
)"""

    def _render_growth(self, plan: dict[str, Any]) -> RenderedQuery:
        metric = self._get_metric(plan["base_metric_id"])
        table_id = plan.get("source_table") or metric["source_table"]
        window_years = int(plan["window_years"])
        outlier_clause = self._growth_outlier_clause(plan)
        sql = f"""
{READ_ONLY_CTE_HINT}
WITH series AS (
  SELECT
    base.geo_level,
    base.geo_id,
    base.geo_name,
    base.year,
    base.{metric["source_column"]} AS metric_value,
    LAG(base.{metric["source_column"]}, {window_years}) OVER (
      PARTITION BY base.geo_level, base.geo_id
      ORDER BY base.year
    ) AS prior_value
  FROM {self._qualified_table(table_id)} AS base
  WHERE base.geo_level = {self._sql_literal(plan["geo_level"])}
    {self._render_filter_clauses(plan, table_id)}
    {self._render_geo_ids_clause(plan.get("geo_ids"), "base.geo_id")}
    AND base.year <= {self._sql_literal(plan["end_year"])}
    AND base.{metric["source_column"]} IS NOT NULL
)
SELECT
  geo_level,
  geo_id,
  geo_name,
  year AS end_year,
  {window_years} AS window_years,
  metric_value AS current_value,
  prior_value,
  CASE
    WHEN prior_value IS NULL OR prior_value = 0 THEN NULL
    ELSE (metric_value - prior_value) / prior_value
  END AS growth_value,
  '{metric["metric_id"]}' AS base_metric_id
FROM series
WHERE year = {self._sql_literal(plan["end_year"])}
  {outlier_clause}
ORDER BY growth_value {self._sql_sort_direction(plan.get("sort_direction", "desc"))} NULLS LAST, geo_name ASC
{self._render_limit_clause(plan.get("limit"))}
""".strip()
        return self._rendered_query(
            template_id="growth",
            sql=sql,
            table_id=table_id,
            fields={
                "geo_level",
                "geo_id",
                "geo_name",
                "year",
                metric["source_column"],
            }
            | self._filter_fields(plan),
            geo_level=plan["geo_level"],
            metric_ids=[metric["metric_id"]],
            plan=plan,
        )

    def _qualified_table(self, table_id: str) -> str:
        table = self._get_table(table_id)
        return f"{table['schema']}.{table['table_name']}"

    def _base_where_clause(
        self, plan: dict[str, Any], table_id: str, metric: dict[str, Any]
    ) -> str:
        return (
            f"base.geo_level = {self._sql_literal(plan['geo_level'])}"
            f"{self._render_filter_clauses(plan, table_id)}"
            f" AND base.year = {self._sql_literal(plan['year'])}"
            f" AND base.{metric['source_column']} IS NOT NULL"
        )

    def _trend_where_clause(
        self, plan: dict[str, Any], table_id: str, metric: dict[str, Any]
    ) -> str:
        return (
            f"base.geo_level = {self._sql_literal(plan['geo_level'])}"
            f"{self._render_filter_clauses(plan, table_id)}"
            f"{self._render_geo_ids_clause(plan.get('geo_ids'), 'base.geo_id')}"
            f" AND base.year BETWEEN {self._sql_literal(plan['start_year'])} AND {self._sql_literal(plan['end_year'])}"
            f" AND base.{metric['source_column']} IS NOT NULL"
        )

    def _compare_where_clause(
        self, plan: dict[str, Any], table_id: str, metric: dict[str, Any]
    ) -> str:
        return (
            f"base.geo_level = {self._sql_literal(plan['geo_level'])}"
            f"{self._render_geo_ids_clause(plan['geo_ids'], 'base.geo_id')}"
            f" AND base.year = {self._sql_literal(plan['year'])}"
            f"{self._render_filter_clauses(plan, table_id)}"
            f" AND base.{metric['source_column']} IS NOT NULL"
        )

    def _benchmark_where_clause(
        self, plan: dict[str, Any], benchmark_geo_level: str
    ) -> str:
        if plan.get("benchmark_geo_ids"):
            return (
                f"base.geo_level = {self._sql_literal(benchmark_geo_level)}"
                f"{self._render_geo_ids_clause(plan['benchmark_geo_ids'], 'base.geo_id')}"
            )
        return f"base.geo_level = {self._sql_literal(benchmark_geo_level)}"

    def _render_filter_clauses(self, plan: dict[str, Any], table_id: str) -> str:
        filters = plan.get("geo_filters") or {}
        if not filters:
            return ""

        clauses: list[str] = []
        valid_columns = self.catalogs["tables"][table_id]
        geo_field = valid_columns["geo_id_field"]
        level_field = valid_columns["geo_level_field"]
        name_field = valid_columns["geo_name_field"]
        allowed_fields = {geo_field, level_field, name_field, "year"}

        for field, value in filters.items():
            if field not in allowed_fields:
                raise ValueError(f"Unsupported filter field: {field}")
            if isinstance(value, list):
                clauses.append(f"base.{field} IN ({self._sql_list(value)})")
            else:
                clauses.append(f"base.{field} = {self._sql_literal(value)}")

        return "".join(f" AND {clause}" for clause in clauses)

    def _render_geo_ids_clause(
        self, geo_ids: list[str] | None, field_name: str
    ) -> str:
        if not geo_ids:
            return ""
        return f" AND {field_name} IN ({self._sql_list(geo_ids)})"

    def _render_limit_clause(self, limit: int | None) -> str:
        if limit is None:
            return ""
        return f"LIMIT {self._validated_limit(limit)}"

    def _growth_outlier_clause(self, plan: dict[str, Any]) -> str:
        if plan.get("geo_level") != "place":
            return ""
        # Small place baselines generate misleading extreme growth rates; keep the ranking focused on
        # places with at least a modest population in both the prior and current period.
        return "AND prior_value >= 1000 AND metric_value >= 1000"

    def _rendered_query(
        self,
        template_id: str,
        sql: str,
        table_id: str,
        fields: set[str],
        geo_level: str | None,
        metric_ids: list[str],
        plan: dict[str, Any],
    ) -> RenderedQuery:
        joins_used = list(plan.get("joins", []))
        return RenderedQuery(
            template_id=template_id,
            sql=sql,
            tables_used=[table_id],
            fields_used={table_id: fields},
            joins_used=joins_used,
            geo_level=geo_level,
            metric_ids=metric_ids,
            plan=plan,
        )

    def _get_metric(self, metric_id: str) -> dict[str, Any]:
        metric = self.catalogs["metrics"].get(metric_id)
        if metric is None or metric.get("status") != "active":
            raise ValueError(f"Unknown or inactive metric_id: {metric_id}")
        return metric

    def _validate_required_slots(self, template_id: str, plan: dict[str, Any]) -> None:
        required_slots = self.catalogs["templates"][template_id].get("required_slots", [])
        missing = [slot for slot in required_slots if slot not in plan or plan[slot] in (None, [], "")]
        if missing:
            raise ValueError(
                f"Plan is missing required slots for {template_id}: {', '.join(missing)}"
            )

    def _get_table(self, table_id: str) -> dict[str, Any]:
        table = self.catalogs["tables"].get(table_id)
        if table is None:
            raise ValueError(f"Unknown table_id: {table_id}")
        return table

    def _filter_fields(self, plan: dict[str, Any]) -> set[str]:
        filters = plan.get("geo_filters") or {}
        return set(filters.keys())

    def _validated_limit(self, limit: Any) -> int:
        limit_value = int(limit)
        if limit_value <= 0:
            raise ValueError("limit must be positive")
        return limit_value

    def _sql_sort_direction(self, sort_direction: str | None) -> str:
        direction = (sort_direction or "desc").lower()
        if direction not in {"asc", "desc"}:
            raise ValueError(f"Unsupported sort_direction: {sort_direction}")
        return direction.upper()

    def _preserve_order_case(self, field_name: str, values: list[str]) -> str:
        when_clauses = [
            f"WHEN {field_name} = {self._sql_literal(value)} THEN {index}"
            for index, value in enumerate(values)
        ]
        return "CASE " + " ".join(when_clauses) + f" ELSE {len(values)} END"

    def _sql_list(self, values: list[Any]) -> str:
        return ", ".join(self._sql_literal(value) for value in values)

    def _sql_literal(self, value: Any) -> str:
        if isinstance(value, bool):
            return "TRUE" if value else "FALSE"
        if isinstance(value, (int, float)):
            return str(value)
        return f"'{self._escape_sql_string(str(value))}'"

    def _escape_sql_string(self, value: str) -> str:
        return value.replace("'", "''")
