-- This script creates the Gold LEHD LODES mart.
-- It joins the workplace-side WAC and residence-side RAC Silver tables onto
-- one shared geography-year surface, then adds a compact set of spatial labor
-- mismatch metrics that are useful in tract-first Deep Dive analysis.

create or replace table patterns_in_place.gold.economics_lodes_wide as

with wac as (
  select *
  from patterns_in_place.silver.lehd_lodes_wac
),

rac as (
  select *
  from patterns_in_place.silver.lehd_lodes_rac
),

joined as (
  select
    coalesce(wac.geo_level, rac.geo_level) as geo_level,
    coalesce(wac.geo_id, rac.geo_id) as geo_id,
    coalesce(wac.geo_name, rac.geo_name) as geo_name,
    coalesce(wac.year, rac.year) as year,

    wac.jobs_total,
    wac.jobs_age_29_or_younger,
    wac.jobs_age_30_54,
    wac.jobs_age_55_plus,
    wac.jobs_earnings_low,
    wac.jobs_earnings_mid,
    wac.jobs_earnings_high,
    wac.jobs_edu_less_than_hs,
    wac.jobs_edu_hs_or_some_college,
    wac.jobs_edu_bachelors_or_advanced,
    wac.jobs_edu_not_available,
    wac.jobs_ind_ag_forest_fish_hunt,
    wac.jobs_ind_mining_quarry_oil_gas,
    wac.jobs_ind_utilities,
    wac.jobs_ind_construction,
    wac.jobs_ind_manufacturing,
    wac.jobs_ind_wholesale,
    wac.jobs_ind_retail,
    wac.jobs_ind_transport_warehouse,
    wac.jobs_ind_information,
    wac.jobs_ind_finance_insurance,
    wac.jobs_ind_real_estate,
    wac.jobs_ind_professional_scientific_technical,
    wac.jobs_ind_management_companies,
    wac.jobs_ind_admin_support_waste,
    wac.jobs_ind_educational_services,
    wac.jobs_ind_health_care_social_assistance,
    wac.jobs_ind_arts_entertainment_recreation,
    wac.jobs_ind_accommodation_food,
    wac.jobs_ind_other_services,
    wac.jobs_ind_public_administration,
    wac.jobs_firm_age_0_1,
    wac.jobs_firm_age_2_3,
    wac.jobs_firm_age_4_5,
    wac.jobs_firm_age_6_10,
    wac.jobs_firm_age_11_plus,
    wac.jobs_firm_size_0_19,
    wac.jobs_firm_size_20_49,
    wac.jobs_firm_size_50_249,
    wac.jobs_firm_size_250_499,
    wac.jobs_firm_size_500_plus,
    wac.pct_jobs_age_29_or_younger,
    wac.pct_jobs_age_30_54,
    wac.pct_jobs_age_55_plus,
    wac.pct_jobs_earnings_low,
    wac.pct_jobs_earnings_mid,
    wac.pct_jobs_earnings_high,
    wac.pct_jobs_edu_less_than_hs,
    wac.pct_jobs_edu_hs_or_some_college,
    wac.pct_jobs_edu_bachelors_or_advanced,
    wac.pct_jobs_edu_not_available,
    wac.pct_jobs_ind_ag_forest_fish_hunt,
    wac.pct_jobs_ind_mining_quarry_oil_gas,
    wac.pct_jobs_ind_utilities,
    wac.pct_jobs_ind_construction,
    wac.pct_jobs_ind_manufacturing,
    wac.pct_jobs_ind_wholesale,
    wac.pct_jobs_ind_retail,
    wac.pct_jobs_ind_transport_warehouse,
    wac.pct_jobs_ind_information,
    wac.pct_jobs_ind_finance_insurance,
    wac.pct_jobs_ind_real_estate,
    wac.pct_jobs_ind_professional_scientific_technical,
    wac.pct_jobs_ind_management_companies,
    wac.pct_jobs_ind_admin_support_waste,
    wac.pct_jobs_ind_educational_services,
    wac.pct_jobs_ind_health_care_social_assistance,
    wac.pct_jobs_ind_arts_entertainment_recreation,
    wac.pct_jobs_ind_accommodation_food,
    wac.pct_jobs_ind_other_services,
    wac.pct_jobs_ind_public_administration,
    wac.pct_jobs_firm_age_0_1,
    wac.pct_jobs_firm_age_2_3,
    wac.pct_jobs_firm_age_4_5,
    wac.pct_jobs_firm_age_6_10,
    wac.pct_jobs_firm_age_11_plus,
    wac.pct_jobs_firm_size_0_19,
    wac.pct_jobs_firm_size_20_49,
    wac.pct_jobs_firm_size_50_249,
    wac.pct_jobs_firm_size_250_499,
    wac.pct_jobs_firm_size_500_plus,

    rac.workers_total,
    rac.workers_age_29_or_younger,
    rac.workers_age_30_54,
    rac.workers_age_55_plus,
    rac.workers_earnings_low,
    rac.workers_earnings_mid,
    rac.workers_earnings_high,
    rac.workers_edu_less_than_hs,
    rac.workers_edu_hs_or_some_college,
    rac.workers_edu_bachelors_or_advanced,
    rac.workers_edu_not_available,
    rac.workers_ind_ag_forest_fish_hunt,
    rac.workers_ind_mining_quarry_oil_gas,
    rac.workers_ind_utilities,
    rac.workers_ind_construction,
    rac.workers_ind_manufacturing,
    rac.workers_ind_wholesale,
    rac.workers_ind_retail,
    rac.workers_ind_transport_warehouse,
    rac.workers_ind_information,
    rac.workers_ind_finance_insurance,
    rac.workers_ind_real_estate,
    rac.workers_ind_professional_scientific_technical,
    rac.workers_ind_management_companies,
    rac.workers_ind_admin_support_waste,
    rac.workers_ind_educational_services,
    rac.workers_ind_health_care_social_assistance,
    rac.workers_ind_arts_entertainment_recreation,
    rac.workers_ind_accommodation_food,
    rac.workers_ind_other_services,
    rac.workers_ind_public_administration,
    rac.pct_workers_age_29_or_younger,
    rac.pct_workers_age_30_54,
    rac.pct_workers_age_55_plus,
    rac.pct_workers_earnings_low,
    rac.pct_workers_earnings_mid,
    rac.pct_workers_earnings_high,
    rac.pct_workers_edu_less_than_hs,
    rac.pct_workers_edu_hs_or_some_college,
    rac.pct_workers_edu_bachelors_or_advanced,
    rac.pct_workers_edu_not_available,
    rac.pct_workers_ind_ag_forest_fish_hunt,
    rac.pct_workers_ind_mining_quarry_oil_gas,
    rac.pct_workers_ind_utilities,
    rac.pct_workers_ind_construction,
    rac.pct_workers_ind_manufacturing,
    rac.pct_workers_ind_wholesale,
    rac.pct_workers_ind_retail,
    rac.pct_workers_ind_transport_warehouse,
    rac.pct_workers_ind_information,
    rac.pct_workers_ind_finance_insurance,
    rac.pct_workers_ind_real_estate,
    rac.pct_workers_ind_professional_scientific_technical,
    rac.pct_workers_ind_management_companies,
    rac.pct_workers_ind_admin_support_waste,
    rac.pct_workers_ind_educational_services,
    rac.pct_workers_ind_health_care_social_assistance,
    rac.pct_workers_ind_arts_entertainment_recreation,
    rac.pct_workers_ind_accommodation_food,
    rac.pct_workers_ind_other_services,
    rac.pct_workers_ind_public_administration
  from wac
  full outer join rac
    on wac.geo_level = rac.geo_level
   and wac.geo_id = rac.geo_id
   and wac.geo_name = rac.geo_name
   and wac.year = rac.year
)

select
  *,
  jobs_total - workers_total as jobs_minus_workers,
  workers_total - jobs_total as workers_minus_jobs,
  jobs_total / nullif(workers_total, 0) as jobs_to_workers_ratio,
  workers_total / nullif(jobs_total, 0) as workers_to_jobs_ratio,
  pct_jobs_age_29_or_younger - pct_workers_age_29_or_younger as pct_point_gap_age_29_or_younger,
  pct_jobs_age_30_54 - pct_workers_age_30_54 as pct_point_gap_age_30_54,
  pct_jobs_age_55_plus - pct_workers_age_55_plus as pct_point_gap_age_55_plus,
  pct_jobs_earnings_low - pct_workers_earnings_low as pct_point_gap_earnings_low,
  pct_jobs_earnings_mid - pct_workers_earnings_mid as pct_point_gap_earnings_mid,
  pct_jobs_earnings_high - pct_workers_earnings_high as pct_point_gap_earnings_high,
  pct_jobs_edu_less_than_hs - pct_workers_edu_less_than_hs as pct_point_gap_edu_less_than_hs,
  pct_jobs_edu_hs_or_some_college - pct_workers_edu_hs_or_some_college as pct_point_gap_edu_hs_or_some_college,
  pct_jobs_edu_bachelors_or_advanced - pct_workers_edu_bachelors_or_advanced as pct_point_gap_edu_bachelors_or_advanced,
  pct_jobs_edu_not_available - pct_workers_edu_not_available as pct_point_gap_edu_not_available,
  pct_jobs_ind_ag_forest_fish_hunt - pct_workers_ind_ag_forest_fish_hunt as pct_point_gap_ind_ag_forest_fish_hunt,
  pct_jobs_ind_mining_quarry_oil_gas - pct_workers_ind_mining_quarry_oil_gas as pct_point_gap_ind_mining_quarry_oil_gas,
  pct_jobs_ind_utilities - pct_workers_ind_utilities as pct_point_gap_ind_utilities,
  pct_jobs_ind_construction - pct_workers_ind_construction as pct_point_gap_ind_construction,
  pct_jobs_ind_manufacturing - pct_workers_ind_manufacturing as pct_point_gap_ind_manufacturing,
  pct_jobs_ind_wholesale - pct_workers_ind_wholesale as pct_point_gap_ind_wholesale,
  pct_jobs_ind_retail - pct_workers_ind_retail as pct_point_gap_ind_retail,
  pct_jobs_ind_transport_warehouse - pct_workers_ind_transport_warehouse as pct_point_gap_ind_transport_warehouse,
  pct_jobs_ind_information - pct_workers_ind_information as pct_point_gap_ind_information,
  pct_jobs_ind_finance_insurance - pct_workers_ind_finance_insurance as pct_point_gap_ind_finance_insurance,
  pct_jobs_ind_real_estate - pct_workers_ind_real_estate as pct_point_gap_ind_real_estate,
  pct_jobs_ind_professional_scientific_technical - pct_workers_ind_professional_scientific_technical as pct_point_gap_ind_professional_scientific_technical,
  pct_jobs_ind_management_companies - pct_workers_ind_management_companies as pct_point_gap_ind_management_companies,
  pct_jobs_ind_admin_support_waste - pct_workers_ind_admin_support_waste as pct_point_gap_ind_admin_support_waste,
  pct_jobs_ind_educational_services - pct_workers_ind_educational_services as pct_point_gap_ind_educational_services,
  pct_jobs_ind_health_care_social_assistance - pct_workers_ind_health_care_social_assistance as pct_point_gap_ind_health_care_social_assistance,
  pct_jobs_ind_arts_entertainment_recreation - pct_workers_ind_arts_entertainment_recreation as pct_point_gap_ind_arts_entertainment_recreation,
  pct_jobs_ind_accommodation_food - pct_workers_ind_accommodation_food as pct_point_gap_ind_accommodation_food,
  pct_jobs_ind_other_services - pct_workers_ind_other_services as pct_point_gap_ind_other_services,
  pct_jobs_ind_public_administration - pct_workers_ind_public_administration as pct_point_gap_ind_public_administration
from joined
